### PR TITLE
Added scripts for building and testing

### PR DESCRIPTION
**Pull request by vytis**
This will be downloaded from other project's `circle.yml` to be able to run and test a framework. It will enable us to have all configuration in one place instead of scattered in multiple CI configs.

### CODE REVIEW

**Comment by vytis** [comment]
Do not merge yet, let's wait until I add several other frameworks just to verify that I didn't miss any other things

**Comment by daehn** [comment]
@vytis we need to add this repo here to the frameworks list in the scripts and re-run the label creation

**Comment by daehn** [comment]
To create the `DO NOT MERGE` (and others) label here as well

**Comment by vytis** [comment]
It seems I don't have enough permissions to create labels from UI though...

**Comment by daehn** [comment]
Yeah, me neither :(

**Pull request merged**
